seo:
  title: "The Solimans | Fuel For Champions"
  description: "A health and fitness meal plan business that believes healthy eating doesn’t have to be boring. Dietitian-designed and chef-crafted."
  site_name: "The Solimans"
  social_image: "/images/2.webp"
  favicon_image: "/images/the-solimans-logo-white.webp"
